name: Deploy to AWS Elastic Beanstalk using Docker

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-react-app .

    - name: Package Docker image for Elastic Beanstalk
      run: |
        mkdir -p docker-build
        docker save my-react-app:latest > docker-build/my-react-app.tar
        echo '{
          "AWSEBDockerrunVersion": "1",
          "Image": {
            "Name": "my-react-app:latest",
            "Update": "true"
          },
          "Ports": [
            {
              "ContainerPort": "3000"
            }
          ]
        }' > docker-build/Dockerrun.aws.json
        cd docker-build && zip -r ../docker-build.zip .

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: react-elastic-beanstalk
        environment_name: e-prfcte7sni
        version_label: ${{ github.run_id }}
        region: ap-south-1  # or your AWS region
        zip_file: docker-build.zip
